-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity abs_custom is
port (
    ap_ready : OUT STD_LOGIC;
    number_V : IN STD_LOGIC_VECTOR (16 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (16 downto 0) );
end;


architecture behav of abs_custom is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_16_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln703_fu_24_p2 : STD_LOGIC_VECTOR (16 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        sub_ln703_fu_24_p2 when (tmp_fu_16_p3(0) = '1') else 
        number_V;
    sub_ln703_fu_24_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(number_V));
    tmp_fu_16_p3 <= number_V(16 downto 16);
end behav;
