// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kmeans.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kmeans::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kmeans::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<31> kmeans::ap_ST_fsm_state1 = "1";
const sc_lv<31> kmeans::ap_ST_fsm_state2 = "10";
const sc_lv<31> kmeans::ap_ST_fsm_state3 = "100";
const sc_lv<31> kmeans::ap_ST_fsm_state4 = "1000";
const sc_lv<31> kmeans::ap_ST_fsm_state5 = "10000";
const sc_lv<31> kmeans::ap_ST_fsm_state6 = "100000";
const sc_lv<31> kmeans::ap_ST_fsm_state7 = "1000000";
const sc_lv<31> kmeans::ap_ST_fsm_state8 = "10000000";
const sc_lv<31> kmeans::ap_ST_fsm_state9 = "100000000";
const sc_lv<31> kmeans::ap_ST_fsm_state10 = "1000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state11 = "10000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state12 = "100000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<31> kmeans::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<32> kmeans::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> kmeans::ap_const_lv32_1 = "1";
const sc_lv<32> kmeans::ap_const_lv32_2 = "10";
const sc_lv<32> kmeans::ap_const_lv32_3 = "11";
const sc_lv<1> kmeans::ap_const_lv1_0 = "0";
const sc_lv<32> kmeans::ap_const_lv32_4 = "100";
const sc_lv<32> kmeans::ap_const_lv32_5 = "101";
const sc_lv<32> kmeans::ap_const_lv32_7 = "111";
const sc_lv<32> kmeans::ap_const_lv32_8 = "1000";
const sc_lv<1> kmeans::ap_const_lv1_1 = "1";
const sc_lv<32> kmeans::ap_const_lv32_9 = "1001";
const sc_lv<2> kmeans::ap_const_lv2_0 = "00";
const sc_lv<32> kmeans::ap_const_lv32_6 = "110";
const sc_lv<6> kmeans::ap_const_lv6_0 = "000000";
const sc_lv<32> kmeans::ap_const_lv32_1E = "11110";
const sc_lv<17> kmeans::ap_const_lv17_0 = "00000000000000000";
const sc_lv<2> kmeans::ap_const_lv2_2 = "10";
const sc_lv<2> kmeans::ap_const_lv2_1 = "1";
const sc_lv<10> kmeans::ap_const_lv10_0 = "0000000000";
const sc_lv<6> kmeans::ap_const_lv6_32 = "110010";
const sc_lv<6> kmeans::ap_const_lv6_1 = "1";
const sc_lv<32> kmeans::ap_const_lv32_10 = "10000";
const bool kmeans::ap_const_boolean_1 = true;

kmeans::kmeans(sc_module_name name) : sc_module(name), mVcdFile(0) {
    x_data_V_U = new kmeans_x_data_V("x_data_V_U");
    x_data_V_U->clk(ap_clk);
    x_data_V_U->reset(ap_rst);
    x_data_V_U->address0(x_data_V_address0);
    x_data_V_U->ce0(x_data_V_ce0);
    x_data_V_U->q0(x_data_V_q0);
    y_data_V_U = new kmeans_y_data_V("y_data_V_U");
    y_data_V_U->clk(ap_clk);
    y_data_V_U->reset(ap_rst);
    y_data_V_U->address0(y_data_V_address0);
    y_data_V_U->ce0(y_data_V_ce0);
    y_data_V_U->q0(y_data_V_q0);
    data_cluster_id_U = new kmeans_data_clustbkb("data_cluster_id_U");
    data_cluster_id_U->clk(ap_clk);
    data_cluster_id_U->reset(ap_rst);
    data_cluster_id_U->address0(data_cluster_id_address0);
    data_cluster_id_U->ce0(data_cluster_id_ce0);
    data_cluster_id_U->we0(data_cluster_id_we0);
    data_cluster_id_U->d0(data_cluster_id_d0);
    data_cluster_id_U->q0(data_cluster_id_q0);
    kmeans_sdiv_18s_3cud_U1 = new kmeans_sdiv_18s_3cud<1,22,18,32,17>("kmeans_sdiv_18s_3cud_U1");
    kmeans_sdiv_18s_3cud_U1->clk(ap_clk);
    kmeans_sdiv_18s_3cud_U1->reset(ap_rst);
    kmeans_sdiv_18s_3cud_U1->start(grp_fu_482_ap_start);
    kmeans_sdiv_18s_3cud_U1->done(grp_fu_482_ap_done);
    kmeans_sdiv_18s_3cud_U1->din0(grp_fu_482_p0);
    kmeans_sdiv_18s_3cud_U1->din1(i_op_assign_0_reg_244);
    kmeans_sdiv_18s_3cud_U1->ce(ap_var_for_const0);
    kmeans_sdiv_18s_3cud_U1->dout(grp_fu_482_p2);
    kmeans_sdiv_18s_3cud_U2 = new kmeans_sdiv_18s_3cud<1,22,18,32,17>("kmeans_sdiv_18s_3cud_U2");
    kmeans_sdiv_18s_3cud_U2->clk(ap_clk);
    kmeans_sdiv_18s_3cud_U2->reset(ap_rst);
    kmeans_sdiv_18s_3cud_U2->start(grp_fu_492_ap_start);
    kmeans_sdiv_18s_3cud_U2->done(grp_fu_492_ap_done);
    kmeans_sdiv_18s_3cud_U2->din0(grp_fu_492_p0);
    kmeans_sdiv_18s_3cud_U2->din1(i_op_assign_0_reg_244);
    kmeans_sdiv_18s_3cud_U2->ce(ap_var_for_const0);
    kmeans_sdiv_18s_3cud_U2->dout(grp_fu_492_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln30_fu_298_p2);
    sensitive << ( i_1_0_reg_186 );

    SC_METHOD(thread_add_ln44_fu_447_p2);
    sensitive << ( i_2_0_reg_197 );

    SC_METHOD(thread_add_ln49_fu_459_p2);
    sensitive << ( j_1_0_reg_233 );

    SC_METHOD(thread_add_ln53_fu_528_p2);
    sensitive << ( i_op_assign_0_reg_244 );

    SC_METHOD(thread_add_ln703_1_fu_430_p2);
    sensitive << ( select_ln4_2_fu_395_p3 );
    sensitive << ( select_ln4_3_fu_422_p3 );

    SC_METHOD(thread_add_ln703_2_fu_512_p2);
    sensitive << ( p_Val2_13_0_reg_209 );
    sensitive << ( sext_ln1265_2_fu_508_p1 );

    SC_METHOD(thread_add_ln703_3_fu_522_p2);
    sensitive << ( p_Val2_15_0_reg_221 );
    sensitive << ( sext_ln1265_3_fu_518_p1 );

    SC_METHOD(thread_add_ln703_fu_370_p2);
    sensitive << ( select_ln4_fu_332_p3 );
    sensitive << ( select_ln4_1_fu_362_p3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln44_fu_441_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln44_fu_441_p2 );

    SC_METHOD(thread_centroids_x_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );
    sensitive << ( zext_ln20_fu_268_p1 );

    SC_METHOD(thread_centroids_x_V_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( zext_ln58_fu_558_p1 );

    SC_METHOD(thread_centroids_x_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );

    SC_METHOD(thread_centroids_x_V_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_centroids_x_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );
    sensitive << ( zext_ln731_fu_286_p1 );

    SC_METHOD(thread_centroids_x_V_d1);
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( grp_fu_482_p2 );

    SC_METHOD(thread_centroids_x_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );

    SC_METHOD(thread_centroids_x_V_we1);
    sensitive << ( icmp_ln57_reg_676 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_centroids_y_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );
    sensitive << ( zext_ln20_fu_268_p1 );

    SC_METHOD(thread_centroids_y_V_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( zext_ln58_fu_558_p1 );

    SC_METHOD(thread_centroids_y_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );

    SC_METHOD(thread_centroids_y_V_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_centroids_y_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );
    sensitive << ( zext_ln731_fu_286_p1 );

    SC_METHOD(thread_centroids_y_V_d1);
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( grp_fu_492_p2 );

    SC_METHOD(thread_centroids_y_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln19_fu_256_p2 );

    SC_METHOD(thread_centroids_y_V_we1);
    sensitive << ( icmp_ln57_reg_676 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_data_cluster_id_address0);
    sensitive << ( zext_ln31_reg_610 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln50_fu_465_p1 );

    SC_METHOD(thread_data_cluster_id_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_data_cluster_id_d0);
    sensitive << ( add_ln703_reg_635 );
    sensitive << ( add_ln703_1_reg_640 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_data_cluster_id_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_482_ap_start);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln49_fu_453_p2 );
    sensitive << ( icmp_ln57_fu_472_p2 );

    SC_METHOD(thread_grp_fu_482_p0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_13_0_reg_209 );

    SC_METHOD(thread_grp_fu_492_ap_start);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln49_fu_453_p2 );
    sensitive << ( icmp_ln57_fu_472_p2 );

    SC_METHOD(thread_grp_fu_492_p0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_15_0_reg_221 );

    SC_METHOD(thread_i_fu_262_p2);
    sensitive << ( p_Val2_s_reg_175 );

    SC_METHOD(thread_icmp_ln19_fu_256_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_Val2_s_reg_175 );

    SC_METHOD(thread_icmp_ln30_fu_292_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_1_0_reg_186 );

    SC_METHOD(thread_icmp_ln44_fu_441_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i_2_0_reg_197 );

    SC_METHOD(thread_icmp_ln49_fu_453_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( j_1_0_reg_233 );

    SC_METHOD(thread_icmp_ln50_fu_502_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i_2_0_reg_197 );
    sensitive << ( zext_ln50_1_fu_498_p1 );

    SC_METHOD(thread_icmp_ln57_fu_472_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln49_fu_453_p2 );
    sensitive << ( i_op_assign_0_reg_244 );

    SC_METHOD(thread_select_ln4_1_fu_362_p3);
    sensitive << ( sub_ln703_1_fu_343_p2 );
    sensitive << ( tmp_1_fu_348_p3 );
    sensitive << ( sub_ln703_5_fu_356_p2 );

    SC_METHOD(thread_select_ln4_2_fu_395_p3);
    sensitive << ( sub_ln703_2_fu_376_p2 );
    sensitive << ( tmp_2_fu_381_p3 );
    sensitive << ( sub_ln703_6_fu_389_p2 );

    SC_METHOD(thread_select_ln4_3_fu_422_p3);
    sensitive << ( sub_ln703_3_fu_403_p2 );
    sensitive << ( tmp_3_fu_408_p3 );
    sensitive << ( sub_ln703_7_fu_416_p2 );

    SC_METHOD(thread_select_ln4_fu_332_p3);
    sensitive << ( sub_ln703_fu_313_p2 );
    sensitive << ( tmp_fu_318_p3 );
    sensitive << ( sub_ln703_4_fu_326_p2 );

    SC_METHOD(thread_select_ln50_1_fu_542_p3);
    sensitive << ( p_Val2_15_0_reg_221 );
    sensitive << ( icmp_ln50_fu_502_p2 );
    sensitive << ( add_ln703_3_fu_522_p2 );

    SC_METHOD(thread_select_ln50_2_fu_550_p3);
    sensitive << ( i_op_assign_0_reg_244 );
    sensitive << ( icmp_ln50_fu_502_p2 );
    sensitive << ( add_ln53_fu_528_p2 );

    SC_METHOD(thread_select_ln50_fu_534_p3);
    sensitive << ( p_Val2_13_0_reg_209 );
    sensitive << ( icmp_ln50_fu_502_p2 );
    sensitive << ( add_ln703_2_fu_512_p2 );

    SC_METHOD(thread_sext_ln1265_1_fu_340_p1);
    sensitive << ( y_data_V_load_reg_630 );

    SC_METHOD(thread_sext_ln1265_2_fu_508_p1);
    sensitive << ( x_data_V_q0 );

    SC_METHOD(thread_sext_ln1265_3_fu_518_p1);
    sensitive << ( y_data_V_q0 );

    SC_METHOD(thread_sext_ln1265_fu_310_p1);
    sensitive << ( x_data_V_load_reg_625 );

    SC_METHOD(thread_shl_ln_fu_278_p3);
    sensitive << ( trunc_ln731_fu_274_p1 );

    SC_METHOD(thread_sub_ln703_1_fu_343_p2);
    sensitive << ( centroids_y_V_load_reg_587 );
    sensitive << ( sext_ln1265_1_fu_340_p1 );

    SC_METHOD(thread_sub_ln703_2_fu_376_p2);
    sensitive << ( centroids_x_V_load_1_reg_592 );
    sensitive << ( sext_ln1265_fu_310_p1 );

    SC_METHOD(thread_sub_ln703_3_fu_403_p2);
    sensitive << ( centroids_y_V_load_1_reg_597 );
    sensitive << ( sext_ln1265_1_fu_340_p1 );

    SC_METHOD(thread_sub_ln703_4_fu_326_p2);
    sensitive << ( sub_ln703_fu_313_p2 );

    SC_METHOD(thread_sub_ln703_5_fu_356_p2);
    sensitive << ( sub_ln703_1_fu_343_p2 );

    SC_METHOD(thread_sub_ln703_6_fu_389_p2);
    sensitive << ( sub_ln703_2_fu_376_p2 );

    SC_METHOD(thread_sub_ln703_7_fu_416_p2);
    sensitive << ( sub_ln703_3_fu_403_p2 );

    SC_METHOD(thread_sub_ln703_fu_313_p2);
    sensitive << ( centroids_x_V_load_reg_582 );
    sensitive << ( sext_ln1265_fu_310_p1 );

    SC_METHOD(thread_tmp_1_fu_348_p3);
    sensitive << ( sub_ln703_1_fu_343_p2 );

    SC_METHOD(thread_tmp_2_fu_381_p3);
    sensitive << ( sub_ln703_2_fu_376_p2 );

    SC_METHOD(thread_tmp_3_fu_408_p3);
    sensitive << ( sub_ln703_3_fu_403_p2 );

    SC_METHOD(thread_tmp_fu_318_p3);
    sensitive << ( sub_ln703_fu_313_p2 );

    SC_METHOD(thread_trunc_ln731_fu_274_p1);
    sensitive << ( p_Val2_s_reg_175 );

    SC_METHOD(thread_x_data_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln31_fu_304_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln50_fu_465_p1 );

    SC_METHOD(thread_x_data_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_y_data_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln31_fu_304_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln50_fu_465_p1 );

    SC_METHOD(thread_y_data_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_zext_ln20_fu_268_p1);
    sensitive << ( p_Val2_s_reg_175 );

    SC_METHOD(thread_zext_ln31_fu_304_p1);
    sensitive << ( i_1_0_reg_186 );

    SC_METHOD(thread_zext_ln50_1_fu_498_p1);
    sensitive << ( data_cluster_id_q0 );

    SC_METHOD(thread_zext_ln50_fu_465_p1);
    sensitive << ( j_1_0_reg_233 );

    SC_METHOD(thread_zext_ln58_fu_558_p1);
    sensitive << ( i_2_0_reg_197 );

    SC_METHOD(thread_zext_ln731_fu_286_p1);
    sensitive << ( shl_ln_fu_278_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln30_fu_292_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln49_fu_453_p2 );
    sensitive << ( icmp_ln57_fu_472_p2 );
    sensitive << ( icmp_ln19_fu_256_p2 );
    sensitive << ( icmp_ln44_fu_441_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kmeans_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, centroids_x_V_address0, "(port)centroids_x_V_address0");
    sc_trace(mVcdFile, centroids_x_V_ce0, "(port)centroids_x_V_ce0");
    sc_trace(mVcdFile, centroids_x_V_we0, "(port)centroids_x_V_we0");
    sc_trace(mVcdFile, centroids_x_V_d0, "(port)centroids_x_V_d0");
    sc_trace(mVcdFile, centroids_x_V_q0, "(port)centroids_x_V_q0");
    sc_trace(mVcdFile, centroids_x_V_address1, "(port)centroids_x_V_address1");
    sc_trace(mVcdFile, centroids_x_V_ce1, "(port)centroids_x_V_ce1");
    sc_trace(mVcdFile, centroids_x_V_we1, "(port)centroids_x_V_we1");
    sc_trace(mVcdFile, centroids_x_V_d1, "(port)centroids_x_V_d1");
    sc_trace(mVcdFile, centroids_x_V_q1, "(port)centroids_x_V_q1");
    sc_trace(mVcdFile, centroids_y_V_address0, "(port)centroids_y_V_address0");
    sc_trace(mVcdFile, centroids_y_V_ce0, "(port)centroids_y_V_ce0");
    sc_trace(mVcdFile, centroids_y_V_we0, "(port)centroids_y_V_we0");
    sc_trace(mVcdFile, centroids_y_V_d0, "(port)centroids_y_V_d0");
    sc_trace(mVcdFile, centroids_y_V_q0, "(port)centroids_y_V_q0");
    sc_trace(mVcdFile, centroids_y_V_address1, "(port)centroids_y_V_address1");
    sc_trace(mVcdFile, centroids_y_V_ce1, "(port)centroids_y_V_ce1");
    sc_trace(mVcdFile, centroids_y_V_we1, "(port)centroids_y_V_we1");
    sc_trace(mVcdFile, centroids_y_V_d1, "(port)centroids_y_V_d1");
    sc_trace(mVcdFile, centroids_y_V_q1, "(port)centroids_y_V_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, x_data_V_address0, "x_data_V_address0");
    sc_trace(mVcdFile, x_data_V_ce0, "x_data_V_ce0");
    sc_trace(mVcdFile, x_data_V_q0, "x_data_V_q0");
    sc_trace(mVcdFile, y_data_V_address0, "y_data_V_address0");
    sc_trace(mVcdFile, y_data_V_ce0, "y_data_V_ce0");
    sc_trace(mVcdFile, y_data_V_q0, "y_data_V_q0");
    sc_trace(mVcdFile, i_fu_262_p2, "i_fu_262_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, centroids_x_V_load_reg_582, "centroids_x_V_load_reg_582");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, centroids_y_V_load_reg_587, "centroids_y_V_load_reg_587");
    sc_trace(mVcdFile, centroids_x_V_load_1_reg_592, "centroids_x_V_load_1_reg_592");
    sc_trace(mVcdFile, centroids_y_V_load_1_reg_597, "centroids_y_V_load_1_reg_597");
    sc_trace(mVcdFile, add_ln30_fu_298_p2, "add_ln30_fu_298_p2");
    sc_trace(mVcdFile, add_ln30_reg_605, "add_ln30_reg_605");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln31_fu_304_p1, "zext_ln31_fu_304_p1");
    sc_trace(mVcdFile, zext_ln31_reg_610, "zext_ln31_reg_610");
    sc_trace(mVcdFile, icmp_ln30_fu_292_p2, "icmp_ln30_fu_292_p2");
    sc_trace(mVcdFile, x_data_V_load_reg_625, "x_data_V_load_reg_625");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, y_data_V_load_reg_630, "y_data_V_load_reg_630");
    sc_trace(mVcdFile, add_ln703_fu_370_p2, "add_ln703_fu_370_p2");
    sc_trace(mVcdFile, add_ln703_reg_635, "add_ln703_reg_635");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, add_ln703_1_fu_430_p2, "add_ln703_1_fu_430_p2");
    sc_trace(mVcdFile, add_ln703_1_reg_640, "add_ln703_1_reg_640");
    sc_trace(mVcdFile, add_ln44_fu_447_p2, "add_ln44_fu_447_p2");
    sc_trace(mVcdFile, add_ln44_reg_648, "add_ln44_reg_648");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln49_fu_459_p2, "add_ln49_fu_459_p2");
    sc_trace(mVcdFile, add_ln49_reg_656, "add_ln49_reg_656");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln49_fu_453_p2, "icmp_ln49_fu_453_p2");
    sc_trace(mVcdFile, icmp_ln57_fu_472_p2, "icmp_ln57_fu_472_p2");
    sc_trace(mVcdFile, icmp_ln57_reg_676, "icmp_ln57_reg_676");
    sc_trace(mVcdFile, select_ln50_fu_534_p3, "select_ln50_fu_534_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, select_ln50_1_fu_542_p3, "select_ln50_1_fu_542_p3");
    sc_trace(mVcdFile, select_ln50_2_fu_550_p3, "select_ln50_2_fu_550_p3");
    sc_trace(mVcdFile, data_cluster_id_address0, "data_cluster_id_address0");
    sc_trace(mVcdFile, data_cluster_id_ce0, "data_cluster_id_ce0");
    sc_trace(mVcdFile, data_cluster_id_we0, "data_cluster_id_we0");
    sc_trace(mVcdFile, data_cluster_id_d0, "data_cluster_id_d0");
    sc_trace(mVcdFile, data_cluster_id_q0, "data_cluster_id_q0");
    sc_trace(mVcdFile, p_Val2_s_reg_175, "p_Val2_s_reg_175");
    sc_trace(mVcdFile, icmp_ln19_fu_256_p2, "icmp_ln19_fu_256_p2");
    sc_trace(mVcdFile, i_1_0_reg_186, "i_1_0_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_2_0_reg_197, "i_2_0_reg_197");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, p_Val2_13_0_reg_209, "p_Val2_13_0_reg_209");
    sc_trace(mVcdFile, icmp_ln44_fu_441_p2, "icmp_ln44_fu_441_p2");
    sc_trace(mVcdFile, p_Val2_15_0_reg_221, "p_Val2_15_0_reg_221");
    sc_trace(mVcdFile, j_1_0_reg_233, "j_1_0_reg_233");
    sc_trace(mVcdFile, i_op_assign_0_reg_244, "i_op_assign_0_reg_244");
    sc_trace(mVcdFile, zext_ln20_fu_268_p1, "zext_ln20_fu_268_p1");
    sc_trace(mVcdFile, zext_ln50_fu_465_p1, "zext_ln50_fu_465_p1");
    sc_trace(mVcdFile, zext_ln58_fu_558_p1, "zext_ln58_fu_558_p1");
    sc_trace(mVcdFile, zext_ln731_fu_286_p1, "zext_ln731_fu_286_p1");
    sc_trace(mVcdFile, trunc_ln731_fu_274_p1, "trunc_ln731_fu_274_p1");
    sc_trace(mVcdFile, shl_ln_fu_278_p3, "shl_ln_fu_278_p3");
    sc_trace(mVcdFile, sext_ln1265_fu_310_p1, "sext_ln1265_fu_310_p1");
    sc_trace(mVcdFile, sub_ln703_fu_313_p2, "sub_ln703_fu_313_p2");
    sc_trace(mVcdFile, tmp_fu_318_p3, "tmp_fu_318_p3");
    sc_trace(mVcdFile, sub_ln703_4_fu_326_p2, "sub_ln703_4_fu_326_p2");
    sc_trace(mVcdFile, sext_ln1265_1_fu_340_p1, "sext_ln1265_1_fu_340_p1");
    sc_trace(mVcdFile, sub_ln703_1_fu_343_p2, "sub_ln703_1_fu_343_p2");
    sc_trace(mVcdFile, tmp_1_fu_348_p3, "tmp_1_fu_348_p3");
    sc_trace(mVcdFile, sub_ln703_5_fu_356_p2, "sub_ln703_5_fu_356_p2");
    sc_trace(mVcdFile, select_ln4_fu_332_p3, "select_ln4_fu_332_p3");
    sc_trace(mVcdFile, select_ln4_1_fu_362_p3, "select_ln4_1_fu_362_p3");
    sc_trace(mVcdFile, sub_ln703_2_fu_376_p2, "sub_ln703_2_fu_376_p2");
    sc_trace(mVcdFile, tmp_2_fu_381_p3, "tmp_2_fu_381_p3");
    sc_trace(mVcdFile, sub_ln703_6_fu_389_p2, "sub_ln703_6_fu_389_p2");
    sc_trace(mVcdFile, sub_ln703_3_fu_403_p2, "sub_ln703_3_fu_403_p2");
    sc_trace(mVcdFile, tmp_3_fu_408_p3, "tmp_3_fu_408_p3");
    sc_trace(mVcdFile, sub_ln703_7_fu_416_p2, "sub_ln703_7_fu_416_p2");
    sc_trace(mVcdFile, select_ln4_2_fu_395_p3, "select_ln4_2_fu_395_p3");
    sc_trace(mVcdFile, select_ln4_3_fu_422_p3, "select_ln4_3_fu_422_p3");
    sc_trace(mVcdFile, grp_fu_482_p0, "grp_fu_482_p0");
    sc_trace(mVcdFile, grp_fu_492_p0, "grp_fu_492_p0");
    sc_trace(mVcdFile, zext_ln50_1_fu_498_p1, "zext_ln50_1_fu_498_p1");
    sc_trace(mVcdFile, sext_ln1265_2_fu_508_p1, "sext_ln1265_2_fu_508_p1");
    sc_trace(mVcdFile, sext_ln1265_3_fu_518_p1, "sext_ln1265_3_fu_518_p1");
    sc_trace(mVcdFile, icmp_ln50_fu_502_p2, "icmp_ln50_fu_502_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_512_p2, "add_ln703_2_fu_512_p2");
    sc_trace(mVcdFile, add_ln703_3_fu_522_p2, "add_ln703_3_fu_522_p2");
    sc_trace(mVcdFile, add_ln53_fu_528_p2, "add_ln53_fu_528_p2");
    sc_trace(mVcdFile, grp_fu_482_p2, "grp_fu_482_p2");
    sc_trace(mVcdFile, grp_fu_492_p2, "grp_fu_492_p2");
    sc_trace(mVcdFile, grp_fu_482_ap_start, "grp_fu_482_ap_start");
    sc_trace(mVcdFile, grp_fu_482_ap_done, "grp_fu_482_ap_done");
    sc_trace(mVcdFile, grp_fu_492_ap_start, "grp_fu_492_ap_start");
    sc_trace(mVcdFile, grp_fu_492_ap_done, "grp_fu_492_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("kmeans.hdltvin.dat");
    mHdltvoutHandle.open("kmeans.hdltvout.dat");
}

kmeans::~kmeans() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete x_data_V_U;
    delete y_data_V_U;
    delete data_cluster_id_U;
    delete kmeans_sdiv_18s_3cud_U1;
    delete kmeans_sdiv_18s_3cud_U2;
}

void kmeans::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void kmeans::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_0_reg_186 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_1_0_reg_186 = add_ln30_reg_605.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln30_fu_292_p2.read(), ap_const_lv1_1))) {
        i_2_0_reg_197 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        i_2_0_reg_197 = add_ln44_reg_648.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln44_fu_441_p2.read()))) {
        i_op_assign_0_reg_244 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_op_assign_0_reg_244 = select_ln50_2_fu_550_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln44_fu_441_p2.read()))) {
        j_1_0_reg_233 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_1_0_reg_233 = add_ln49_reg_656.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln44_fu_441_p2.read()))) {
        p_Val2_13_0_reg_209 = ap_const_lv17_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Val2_13_0_reg_209 = select_ln50_fu_534_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln44_fu_441_p2.read()))) {
        p_Val2_15_0_reg_221 = ap_const_lv17_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Val2_15_0_reg_221 = select_ln50_1_fu_542_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read()))) {
        p_Val2_s_reg_175 = i_fu_262_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_s_reg_175 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln30_reg_605 = add_ln30_fu_298_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        add_ln44_reg_648 = add_ln44_fu_447_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln49_reg_656 = add_ln49_fu_459_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln703_1_reg_640 = add_ln703_1_fu_430_p2.read();
        add_ln703_reg_635 = add_ln703_fu_370_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        centroids_x_V_load_1_reg_592 = centroids_x_V_q1.read();
        centroids_x_V_load_reg_582 = centroids_x_V_q0.read();
        centroids_y_V_load_1_reg_597 = centroids_y_V_q1.read();
        centroids_y_V_load_reg_587 = centroids_y_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln49_fu_453_p2.read(), ap_const_lv1_1))) {
        icmp_ln57_reg_676 = icmp_ln57_fu_472_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        x_data_V_load_reg_625 = x_data_V_q0.read();
        y_data_V_load_reg_630 = y_data_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln30_fu_292_p2.read(), ap_const_lv1_0))) {
        zext_ln31_reg_610 = zext_ln31_fu_304_p1.read();
    }
}

void kmeans::thread_add_ln30_fu_298_p2() {
    add_ln30_fu_298_p2 = (!i_1_0_reg_186.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_1_0_reg_186.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void kmeans::thread_add_ln44_fu_447_p2() {
    add_ln44_fu_447_p2 = (!i_2_0_reg_197.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_2_0_reg_197.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void kmeans::thread_add_ln49_fu_459_p2() {
    add_ln49_fu_459_p2 = (!j_1_0_reg_233.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_1_0_reg_233.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void kmeans::thread_add_ln53_fu_528_p2() {
    add_ln53_fu_528_p2 = (!i_op_assign_0_reg_244.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_op_assign_0_reg_244.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void kmeans::thread_add_ln703_1_fu_430_p2() {
    add_ln703_1_fu_430_p2 = (!select_ln4_2_fu_395_p3.read().is_01() || !select_ln4_3_fu_422_p3.read().is_01())? sc_lv<17>(): (sc_biguint<17>(select_ln4_2_fu_395_p3.read()) + sc_biguint<17>(select_ln4_3_fu_422_p3.read()));
}

void kmeans::thread_add_ln703_2_fu_512_p2() {
    add_ln703_2_fu_512_p2 = (!sext_ln1265_2_fu_508_p1.read().is_01() || !p_Val2_13_0_reg_209.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_2_fu_508_p1.read()) + sc_bigint<17>(p_Val2_13_0_reg_209.read()));
}

void kmeans::thread_add_ln703_3_fu_522_p2() {
    add_ln703_3_fu_522_p2 = (!sext_ln1265_3_fu_518_p1.read().is_01() || !p_Val2_15_0_reg_221.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_3_fu_518_p1.read()) + sc_bigint<17>(p_Val2_15_0_reg_221.read()));
}

void kmeans::thread_add_ln703_fu_370_p2() {
    add_ln703_fu_370_p2 = (!select_ln4_fu_332_p3.read().is_01() || !select_ln4_1_fu_362_p3.read().is_01())? sc_lv<17>(): (sc_biguint<17>(select_ln4_fu_332_p3.read()) + sc_biguint<17>(select_ln4_1_fu_362_p3.read()));
}

void kmeans::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void kmeans::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void kmeans::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void kmeans::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void kmeans::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void kmeans::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void kmeans::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void kmeans::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void kmeans::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void kmeans::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void kmeans::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void kmeans::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln44_fu_441_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kmeans::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kmeans::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln44_fu_441_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_x_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_256_p2.read())) {
            centroids_x_V_address0 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read())) {
            centroids_x_V_address0 =  (sc_lv<1>) (zext_ln20_fu_268_p1.read());
        } else {
            centroids_x_V_address0 = "X";
        }
    } else {
        centroids_x_V_address0 = "X";
    }
}

void kmeans::thread_centroids_x_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        centroids_x_V_address1 =  (sc_lv<1>) (zext_ln58_fu_558_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        centroids_x_V_address1 = ap_const_lv1_1;
    } else {
        centroids_x_V_address1 = "X";
    }
}

void kmeans::thread_centroids_x_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_256_p2.read())))) {
        centroids_x_V_ce0 = ap_const_logic_1;
    } else {
        centroids_x_V_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_x_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        centroids_x_V_ce1 = ap_const_logic_1;
    } else {
        centroids_x_V_ce1 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_x_V_d0() {
    centroids_x_V_d0 = zext_ln731_fu_286_p1.read();
}

void kmeans::thread_centroids_x_V_d1() {
    centroids_x_V_d1 = grp_fu_482_p2.read().range(17-1, 0);
}

void kmeans::thread_centroids_x_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read()))) {
        centroids_x_V_we0 = ap_const_logic_1;
    } else {
        centroids_x_V_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_x_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_reg_676.read()))) {
        centroids_x_V_we1 = ap_const_logic_1;
    } else {
        centroids_x_V_we1 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_y_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_256_p2.read())) {
            centroids_y_V_address0 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read())) {
            centroids_y_V_address0 =  (sc_lv<1>) (zext_ln20_fu_268_p1.read());
        } else {
            centroids_y_V_address0 = "X";
        }
    } else {
        centroids_y_V_address0 = "X";
    }
}

void kmeans::thread_centroids_y_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        centroids_y_V_address1 =  (sc_lv<1>) (zext_ln58_fu_558_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        centroids_y_V_address1 = ap_const_lv1_1;
    } else {
        centroids_y_V_address1 = "X";
    }
}

void kmeans::thread_centroids_y_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln19_fu_256_p2.read())))) {
        centroids_y_V_ce0 = ap_const_logic_1;
    } else {
        centroids_y_V_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_y_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        centroids_y_V_ce1 = ap_const_logic_1;
    } else {
        centroids_y_V_ce1 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_y_V_d0() {
    centroids_y_V_d0 = zext_ln731_fu_286_p1.read();
}

void kmeans::thread_centroids_y_V_d1() {
    centroids_y_V_d1 = grp_fu_492_p2.read().range(17-1, 0);
}

void kmeans::thread_centroids_y_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read()))) {
        centroids_y_V_we0 = ap_const_logic_1;
    } else {
        centroids_y_V_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_centroids_y_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_reg_676.read()))) {
        centroids_y_V_we1 = ap_const_logic_1;
    } else {
        centroids_y_V_we1 = ap_const_logic_0;
    }
}

void kmeans::thread_data_cluster_id_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        data_cluster_id_address0 =  (sc_lv<6>) (zext_ln50_fu_465_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        data_cluster_id_address0 =  (sc_lv<6>) (zext_ln31_reg_610.read());
    } else {
        data_cluster_id_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void kmeans::thread_data_cluster_id_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        data_cluster_id_ce0 = ap_const_logic_1;
    } else {
        data_cluster_id_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_data_cluster_id_d0() {
    data_cluster_id_d0 = (!add_ln703_1_reg_640.read().is_01() || !add_ln703_reg_635.read().is_01())? sc_lv<1>(): (sc_bigint<17>(add_ln703_1_reg_640.read()) < sc_bigint<17>(add_ln703_reg_635.read()));
}

void kmeans::thread_data_cluster_id_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        data_cluster_id_we0 = ap_const_logic_1;
    } else {
        data_cluster_id_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_grp_fu_482_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln49_fu_453_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_472_p2.read()))) {
        grp_fu_482_ap_start = ap_const_logic_1;
    } else {
        grp_fu_482_ap_start = ap_const_logic_0;
    }
}

void kmeans::thread_grp_fu_482_p0() {
    grp_fu_482_p0 =  (sc_lv<18>) (esl_sext<32,17>(p_Val2_13_0_reg_209.read()));
}

void kmeans::thread_grp_fu_492_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln49_fu_453_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_472_p2.read()))) {
        grp_fu_492_ap_start = ap_const_logic_1;
    } else {
        grp_fu_492_ap_start = ap_const_logic_0;
    }
}

void kmeans::thread_grp_fu_492_p0() {
    grp_fu_492_p0 =  (sc_lv<18>) (esl_sext<32,17>(p_Val2_15_0_reg_221.read()));
}

void kmeans::thread_i_fu_262_p2() {
    i_fu_262_p2 = (!p_Val2_s_reg_175.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(p_Val2_s_reg_175.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void kmeans::thread_icmp_ln19_fu_256_p2() {
    icmp_ln19_fu_256_p2 = (!p_Val2_s_reg_175.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_s_reg_175.read() == ap_const_lv2_2);
}

void kmeans::thread_icmp_ln30_fu_292_p2() {
    icmp_ln30_fu_292_p2 = (!i_1_0_reg_186.read().is_01() || !ap_const_lv6_32.is_01())? sc_lv<1>(): sc_lv<1>(i_1_0_reg_186.read() == ap_const_lv6_32);
}

void kmeans::thread_icmp_ln44_fu_441_p2() {
    icmp_ln44_fu_441_p2 = (!i_2_0_reg_197.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i_2_0_reg_197.read() == ap_const_lv2_2);
}

void kmeans::thread_icmp_ln49_fu_453_p2() {
    icmp_ln49_fu_453_p2 = (!j_1_0_reg_233.read().is_01() || !ap_const_lv6_32.is_01())? sc_lv<1>(): sc_lv<1>(j_1_0_reg_233.read() == ap_const_lv6_32);
}

void kmeans::thread_icmp_ln50_fu_502_p2() {
    icmp_ln50_fu_502_p2 = (!zext_ln50_1_fu_498_p1.read().is_01() || !i_2_0_reg_197.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln50_1_fu_498_p1.read() == i_2_0_reg_197.read());
}

void kmeans::thread_icmp_ln57_fu_472_p2() {
    icmp_ln57_fu_472_p2 = (!i_op_assign_0_reg_244.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(i_op_assign_0_reg_244.read() == ap_const_lv32_0);
}

void kmeans::thread_select_ln4_1_fu_362_p3() {
    select_ln4_1_fu_362_p3 = (!tmp_1_fu_348_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_1_fu_348_p3.read()[0].to_bool())? sub_ln703_5_fu_356_p2.read(): sub_ln703_1_fu_343_p2.read());
}

void kmeans::thread_select_ln4_2_fu_395_p3() {
    select_ln4_2_fu_395_p3 = (!tmp_2_fu_381_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_2_fu_381_p3.read()[0].to_bool())? sub_ln703_6_fu_389_p2.read(): sub_ln703_2_fu_376_p2.read());
}

void kmeans::thread_select_ln4_3_fu_422_p3() {
    select_ln4_3_fu_422_p3 = (!tmp_3_fu_408_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_3_fu_408_p3.read()[0].to_bool())? sub_ln703_7_fu_416_p2.read(): sub_ln703_3_fu_403_p2.read());
}

void kmeans::thread_select_ln4_fu_332_p3() {
    select_ln4_fu_332_p3 = (!tmp_fu_318_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_fu_318_p3.read()[0].to_bool())? sub_ln703_4_fu_326_p2.read(): sub_ln703_fu_313_p2.read());
}

void kmeans::thread_select_ln50_1_fu_542_p3() {
    select_ln50_1_fu_542_p3 = (!icmp_ln50_fu_502_p2.read()[0].is_01())? sc_lv<17>(): ((icmp_ln50_fu_502_p2.read()[0].to_bool())? add_ln703_3_fu_522_p2.read(): p_Val2_15_0_reg_221.read());
}

void kmeans::thread_select_ln50_2_fu_550_p3() {
    select_ln50_2_fu_550_p3 = (!icmp_ln50_fu_502_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln50_fu_502_p2.read()[0].to_bool())? add_ln53_fu_528_p2.read(): i_op_assign_0_reg_244.read());
}

void kmeans::thread_select_ln50_fu_534_p3() {
    select_ln50_fu_534_p3 = (!icmp_ln50_fu_502_p2.read()[0].is_01())? sc_lv<17>(): ((icmp_ln50_fu_502_p2.read()[0].to_bool())? add_ln703_2_fu_512_p2.read(): p_Val2_13_0_reg_209.read());
}

void kmeans::thread_sext_ln1265_1_fu_340_p1() {
    sext_ln1265_1_fu_340_p1 = esl_sext<17,13>(y_data_V_load_reg_630.read());
}

void kmeans::thread_sext_ln1265_2_fu_508_p1() {
    sext_ln1265_2_fu_508_p1 = esl_sext<17,13>(x_data_V_q0.read());
}

void kmeans::thread_sext_ln1265_3_fu_518_p1() {
    sext_ln1265_3_fu_518_p1 = esl_sext<17,13>(y_data_V_q0.read());
}

void kmeans::thread_sext_ln1265_fu_310_p1() {
    sext_ln1265_fu_310_p1 = esl_sext<17,13>(x_data_V_load_reg_625.read());
}

void kmeans::thread_shl_ln_fu_278_p3() {
    shl_ln_fu_278_p3 = esl_concat<1,10>(trunc_ln731_fu_274_p1.read(), ap_const_lv10_0);
}

void kmeans::thread_sub_ln703_1_fu_343_p2() {
    sub_ln703_1_fu_343_p2 = (!sext_ln1265_1_fu_340_p1.read().is_01() || !centroids_y_V_load_reg_587.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_1_fu_340_p1.read()) - sc_biguint<17>(centroids_y_V_load_reg_587.read()));
}

void kmeans::thread_sub_ln703_2_fu_376_p2() {
    sub_ln703_2_fu_376_p2 = (!sext_ln1265_fu_310_p1.read().is_01() || !centroids_x_V_load_1_reg_592.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_fu_310_p1.read()) - sc_biguint<17>(centroids_x_V_load_1_reg_592.read()));
}

void kmeans::thread_sub_ln703_3_fu_403_p2() {
    sub_ln703_3_fu_403_p2 = (!sext_ln1265_1_fu_340_p1.read().is_01() || !centroids_y_V_load_1_reg_597.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_1_fu_340_p1.read()) - sc_biguint<17>(centroids_y_V_load_1_reg_597.read()));
}

void kmeans::thread_sub_ln703_4_fu_326_p2() {
    sub_ln703_4_fu_326_p2 = (!ap_const_lv17_0.is_01() || !sub_ln703_fu_313_p2.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(sub_ln703_fu_313_p2.read()));
}

void kmeans::thread_sub_ln703_5_fu_356_p2() {
    sub_ln703_5_fu_356_p2 = (!ap_const_lv17_0.is_01() || !sub_ln703_1_fu_343_p2.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(sub_ln703_1_fu_343_p2.read()));
}

void kmeans::thread_sub_ln703_6_fu_389_p2() {
    sub_ln703_6_fu_389_p2 = (!ap_const_lv17_0.is_01() || !sub_ln703_2_fu_376_p2.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(sub_ln703_2_fu_376_p2.read()));
}

void kmeans::thread_sub_ln703_7_fu_416_p2() {
    sub_ln703_7_fu_416_p2 = (!ap_const_lv17_0.is_01() || !sub_ln703_3_fu_403_p2.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(sub_ln703_3_fu_403_p2.read()));
}

void kmeans::thread_sub_ln703_fu_313_p2() {
    sub_ln703_fu_313_p2 = (!sext_ln1265_fu_310_p1.read().is_01() || !centroids_x_V_load_reg_582.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1265_fu_310_p1.read()) - sc_biguint<17>(centroids_x_V_load_reg_582.read()));
}

void kmeans::thread_tmp_1_fu_348_p3() {
    tmp_1_fu_348_p3 = sub_ln703_1_fu_343_p2.read().range(16, 16);
}

void kmeans::thread_tmp_2_fu_381_p3() {
    tmp_2_fu_381_p3 = sub_ln703_2_fu_376_p2.read().range(16, 16);
}

void kmeans::thread_tmp_3_fu_408_p3() {
    tmp_3_fu_408_p3 = sub_ln703_3_fu_403_p2.read().range(16, 16);
}

void kmeans::thread_tmp_fu_318_p3() {
    tmp_fu_318_p3 = sub_ln703_fu_313_p2.read().range(16, 16);
}

void kmeans::thread_trunc_ln731_fu_274_p1() {
    trunc_ln731_fu_274_p1 = p_Val2_s_reg_175.read().range(1-1, 0);
}

void kmeans::thread_x_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_data_V_address0 =  (sc_lv<6>) (zext_ln50_fu_465_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_data_V_address0 =  (sc_lv<6>) (zext_ln31_fu_304_p1.read());
    } else {
        x_data_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void kmeans::thread_x_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        x_data_V_ce0 = ap_const_logic_1;
    } else {
        x_data_V_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_y_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        y_data_V_address0 =  (sc_lv<6>) (zext_ln50_fu_465_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        y_data_V_address0 =  (sc_lv<6>) (zext_ln31_fu_304_p1.read());
    } else {
        y_data_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void kmeans::thread_y_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        y_data_V_ce0 = ap_const_logic_1;
    } else {
        y_data_V_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_zext_ln20_fu_268_p1() {
    zext_ln20_fu_268_p1 = esl_zext<64,2>(p_Val2_s_reg_175.read());
}

void kmeans::thread_zext_ln31_fu_304_p1() {
    zext_ln31_fu_304_p1 = esl_zext<64,6>(i_1_0_reg_186.read());
}

void kmeans::thread_zext_ln50_1_fu_498_p1() {
    zext_ln50_1_fu_498_p1 = esl_zext<2,1>(data_cluster_id_q0.read());
}

void kmeans::thread_zext_ln50_fu_465_p1() {
    zext_ln50_fu_465_p1 = esl_zext<64,6>(j_1_0_reg_233.read());
}

void kmeans::thread_zext_ln58_fu_558_p1() {
    zext_ln58_fu_558_p1 = esl_zext<64,2>(i_2_0_reg_197.read());
}

void kmeans::thread_zext_ln731_fu_286_p1() {
    zext_ln731_fu_286_p1 = esl_zext<17,11>(shl_ln_fu_278_p3.read());
}

void kmeans::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_256_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln30_fu_292_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln44_fu_441_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln49_fu_453_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln57_fu_472_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state31;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln49_fu_453_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_472_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<31>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void kmeans::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_address0\" :  \"" << centroids_x_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_ce0\" :  \"" << centroids_x_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_we0\" :  \"" << centroids_x_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_d0\" :  \"" << centroids_x_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"centroids_x_V_q0\" :  \"" << centroids_x_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_address1\" :  \"" << centroids_x_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_ce1\" :  \"" << centroids_x_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_we1\" :  \"" << centroids_x_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_x_V_d1\" :  \"" << centroids_x_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"centroids_x_V_q1\" :  \"" << centroids_x_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_address0\" :  \"" << centroids_y_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_ce0\" :  \"" << centroids_y_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_we0\" :  \"" << centroids_y_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_d0\" :  \"" << centroids_y_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"centroids_y_V_q0\" :  \"" << centroids_y_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_address1\" :  \"" << centroids_y_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_ce1\" :  \"" << centroids_y_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_we1\" :  \"" << centroids_y_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"centroids_y_V_d1\" :  \"" << centroids_y_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"centroids_y_V_q1\" :  \"" << centroids_y_V_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

