// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kmeans,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.514000,HLS_SYN_LAT=4992,HLS_SYN_TPT=none,HLS_SYN_MEM=270,HLS_SYN_DSP=294,HLS_SYN_FF=83050,HLS_SYN_LUT=41806,HLS_VERSION=2020_1}" *)

module kmeans (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        centroids_x_address0,
        centroids_x_ce0,
        centroids_x_we0,
        centroids_x_d0,
        centroids_x_q0,
        centroids_x_address1,
        centroids_x_ce1,
        centroids_x_we1,
        centroids_x_d1,
        centroids_x_q1,
        centroids_y_address0,
        centroids_y_ce0,
        centroids_y_we0,
        centroids_y_d0,
        centroids_y_q0,
        centroids_y_address1,
        centroids_y_ce1,
        centroids_y_we1,
        centroids_y_d1,
        centroids_y_q1
);

parameter    ap_ST_fsm_state1 = 122'd1;
parameter    ap_ST_fsm_state2 = 122'd2;
parameter    ap_ST_fsm_state3 = 122'd4;
parameter    ap_ST_fsm_state4 = 122'd8;
parameter    ap_ST_fsm_state5 = 122'd16;
parameter    ap_ST_fsm_state6 = 122'd32;
parameter    ap_ST_fsm_state7 = 122'd64;
parameter    ap_ST_fsm_state8 = 122'd128;
parameter    ap_ST_fsm_state9 = 122'd256;
parameter    ap_ST_fsm_state10 = 122'd512;
parameter    ap_ST_fsm_state11 = 122'd1024;
parameter    ap_ST_fsm_state12 = 122'd2048;
parameter    ap_ST_fsm_state13 = 122'd4096;
parameter    ap_ST_fsm_state14 = 122'd8192;
parameter    ap_ST_fsm_state15 = 122'd16384;
parameter    ap_ST_fsm_state16 = 122'd32768;
parameter    ap_ST_fsm_state17 = 122'd65536;
parameter    ap_ST_fsm_state18 = 122'd131072;
parameter    ap_ST_fsm_state19 = 122'd262144;
parameter    ap_ST_fsm_state20 = 122'd524288;
parameter    ap_ST_fsm_state21 = 122'd1048576;
parameter    ap_ST_fsm_state22 = 122'd2097152;
parameter    ap_ST_fsm_state23 = 122'd4194304;
parameter    ap_ST_fsm_state24 = 122'd8388608;
parameter    ap_ST_fsm_state25 = 122'd16777216;
parameter    ap_ST_fsm_state26 = 122'd33554432;
parameter    ap_ST_fsm_state27 = 122'd67108864;
parameter    ap_ST_fsm_state28 = 122'd134217728;
parameter    ap_ST_fsm_state29 = 122'd268435456;
parameter    ap_ST_fsm_state30 = 122'd536870912;
parameter    ap_ST_fsm_state31 = 122'd1073741824;
parameter    ap_ST_fsm_state32 = 122'd2147483648;
parameter    ap_ST_fsm_state33 = 122'd4294967296;
parameter    ap_ST_fsm_state34 = 122'd8589934592;
parameter    ap_ST_fsm_state35 = 122'd17179869184;
parameter    ap_ST_fsm_state36 = 122'd34359738368;
parameter    ap_ST_fsm_state37 = 122'd68719476736;
parameter    ap_ST_fsm_state38 = 122'd137438953472;
parameter    ap_ST_fsm_state39 = 122'd274877906944;
parameter    ap_ST_fsm_state40 = 122'd549755813888;
parameter    ap_ST_fsm_state41 = 122'd1099511627776;
parameter    ap_ST_fsm_state42 = 122'd2199023255552;
parameter    ap_ST_fsm_state43 = 122'd4398046511104;
parameter    ap_ST_fsm_state44 = 122'd8796093022208;
parameter    ap_ST_fsm_state45 = 122'd17592186044416;
parameter    ap_ST_fsm_state46 = 122'd35184372088832;
parameter    ap_ST_fsm_state47 = 122'd70368744177664;
parameter    ap_ST_fsm_state48 = 122'd140737488355328;
parameter    ap_ST_fsm_state49 = 122'd281474976710656;
parameter    ap_ST_fsm_state50 = 122'd562949953421312;
parameter    ap_ST_fsm_state51 = 122'd1125899906842624;
parameter    ap_ST_fsm_state52 = 122'd2251799813685248;
parameter    ap_ST_fsm_state53 = 122'd4503599627370496;
parameter    ap_ST_fsm_state54 = 122'd9007199254740992;
parameter    ap_ST_fsm_state55 = 122'd18014398509481984;
parameter    ap_ST_fsm_state56 = 122'd36028797018963968;
parameter    ap_ST_fsm_state57 = 122'd72057594037927936;
parameter    ap_ST_fsm_state58 = 122'd144115188075855872;
parameter    ap_ST_fsm_state59 = 122'd288230376151711744;
parameter    ap_ST_fsm_state60 = 122'd576460752303423488;
parameter    ap_ST_fsm_state61 = 122'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 122'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 122'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 122'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 122'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 122'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 122'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 122'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 122'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 122'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 122'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 122'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 122'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 122'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 122'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 122'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 122'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 122'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 122'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 122'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 122'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 122'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 122'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 122'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 122'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 122'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 122'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 122'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 122'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 122'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 122'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 122'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 122'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 122'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 122'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 122'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 122'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 122'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 122'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 122'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 122'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 122'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 122'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 122'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 122'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 122'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 122'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 122'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 122'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 122'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 122'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 122'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 122'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 122'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 122'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 122'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 122'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 122'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 122'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 122'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 122'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 122'd2658455991569831745807614120560689152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] centroids_x_address0;
output   centroids_x_ce0;
output   centroids_x_we0;
output  [31:0] centroids_x_d0;
input  [31:0] centroids_x_q0;
output  [0:0] centroids_x_address1;
output   centroids_x_ce1;
output   centroids_x_we1;
output  [31:0] centroids_x_d1;
input  [31:0] centroids_x_q1;
output  [0:0] centroids_y_address0;
output   centroids_y_ce0;
output   centroids_y_we0;
output  [31:0] centroids_y_d0;
input  [31:0] centroids_y_q0;
output  [0:0] centroids_y_address1;
output   centroids_y_ce1;
output   centroids_y_we1;
output  [31:0] centroids_y_d1;
input  [31:0] centroids_y_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] centroids_x_address0;
reg centroids_x_ce0;
reg centroids_x_we0;
reg[0:0] centroids_x_address1;
reg centroids_x_ce1;
reg centroids_x_we1;
reg[0:0] centroids_y_address0;
reg centroids_y_ce0;
reg centroids_y_we0;
reg[0:0] centroids_y_address1;
reg centroids_y_ce1;
reg centroids_y_we1;

(* fsm_encoding = "none" *) reg   [121:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] x_data_address0;
reg    x_data_ce0;
wire   [31:0] x_data_q0;
reg   [5:0] y_data_address0;
reg    y_data_ce0;
wire   [31:0] y_data_q0;
reg   [31:0] reg_467;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state96;
reg   [31:0] reg_474;
wire   [31:0] zext_ln13_fu_481_p1;
wire    ap_CS_fsm_state2;
wire   [1:0] i_fu_492_p2;
reg   [1:0] i_reg_690;
reg   [31:0] centroids_x_load_reg_695;
wire    ap_CS_fsm_state8;
reg   [31:0] centroids_y_load_reg_700;
reg   [31:0] centroids_x_load_1_reg_705;
reg   [31:0] centroids_y_load_1_reg_710;
wire   [5:0] add_ln24_fu_510_p2;
reg   [5:0] add_ln24_reg_718;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln25_fu_516_p1;
reg   [63:0] zext_ln25_reg_723;
wire   [0:0] icmp_ln24_fu_504_p2;
wire   [31:0] grp_fu_401_p2;
reg   [31:0] tmp_s_reg_738;
wire    ap_CS_fsm_state15;
wire   [31:0] grp_fu_405_p2;
reg   [31:0] tmp_2_reg_743;
wire   [31:0] grp_fu_409_p2;
reg   [31:0] tmp_1_reg_748;
wire   [31:0] grp_fu_413_p2;
reg   [31:0] tmp_3_reg_753;
wire   [63:0] grp_fu_443_p1;
reg   [63:0] x_assign_reg_758;
wire    ap_CS_fsm_state17;
wire   [63:0] grp_fu_446_p1;
reg   [63:0] x_assign_1_reg_763;
wire   [63:0] grp_fu_449_p1;
reg   [63:0] x_assign_2_reg_768;
wire   [63:0] grp_fu_452_p1;
reg   [63:0] x_assign_3_reg_773;
wire   [63:0] grp_pow_generic_double_s_fu_285_ap_return;
reg   [63:0] tmp_i_reg_778;
wire    ap_CS_fsm_state84;
wire   [63:0] grp_pow_generic_double_s_fu_314_ap_return;
reg   [63:0] tmp_i1_reg_783;
wire   [63:0] grp_pow_generic_double_s_fu_343_ap_return;
reg   [63:0] tmp_i2_reg_788;
wire   [63:0] grp_pow_generic_double_s_fu_372_ap_return;
reg   [63:0] tmp_i3_reg_793;
wire   [63:0] grp_fu_459_p2;
reg   [63:0] tmp_4_reg_798;
wire    ap_CS_fsm_state89;
wire   [63:0] grp_fu_463_p2;
reg   [63:0] tmp_8_reg_803;
wire   [31:0] grp_fu_437_p1;
reg   [31:0] min_distance_s_reg_808;
wire    ap_CS_fsm_state91;
wire   [31:0] grp_fu_440_p1;
reg   [31:0] distance_reg_814;
wire   [0:0] icmp_ln29_fu_556_p2;
reg   [0:0] icmp_ln29_reg_820;
wire    ap_CS_fsm_state92;
wire   [0:0] icmp_ln29_1_fu_562_p2;
reg   [0:0] icmp_ln29_1_reg_825;
wire   [0:0] icmp_ln29_2_fu_568_p2;
reg   [0:0] icmp_ln29_2_reg_830;
wire   [0:0] icmp_ln29_3_fu_574_p2;
reg   [0:0] icmp_ln29_3_reg_835;
wire   [1:0] add_ln38_fu_607_p2;
reg   [1:0] add_ln38_reg_843;
wire    ap_CS_fsm_state94;
wire   [5:0] add_ln43_fu_619_p2;
reg   [5:0] add_ln43_reg_851;
wire    ap_CS_fsm_state95;
wire   [0:0] icmp_ln43_fu_613_p2;
wire   [0:0] icmp_ln51_fu_632_p2;
reg   [0:0] icmp_ln51_reg_871;
wire   [0:0] icmp_ln44_fu_642_p2;
reg   [0:0] icmp_ln44_reg_875;
wire   [31:0] select_ln44_2_fu_654_p3;
reg   [31:0] select_ln44_2_reg_881;
wire   [31:0] select_ln44_fu_662_p3;
wire    ap_CS_fsm_state101;
wire   [31:0] select_ln44_1_fu_669_p3;
wire   [31:0] grp_fu_431_p1;
reg   [31:0] tmp_5_reg_896;
wire    ap_CS_fsm_state106;
reg   [5:0] data_cluster_id_address0;
reg    data_cluster_id_ce0;
reg    data_cluster_id_we0;
wire   [0:0] data_cluster_id_d0;
wire   [0:0] data_cluster_id_q0;
wire    grp_pow_generic_double_s_fu_285_ap_start;
wire    grp_pow_generic_double_s_fu_285_ap_done;
wire    grp_pow_generic_double_s_fu_285_ap_idle;
wire    grp_pow_generic_double_s_fu_285_ap_ready;
wire    grp_pow_generic_double_s_fu_314_ap_start;
wire    grp_pow_generic_double_s_fu_314_ap_done;
wire    grp_pow_generic_double_s_fu_314_ap_idle;
wire    grp_pow_generic_double_s_fu_314_ap_ready;
wire    grp_pow_generic_double_s_fu_343_ap_start;
wire    grp_pow_generic_double_s_fu_343_ap_done;
wire    grp_pow_generic_double_s_fu_343_ap_idle;
wire    grp_pow_generic_double_s_fu_343_ap_ready;
wire    grp_pow_generic_double_s_fu_372_ap_start;
wire    grp_pow_generic_double_s_fu_372_ap_done;
wire    grp_pow_generic_double_s_fu_372_ap_idle;
wire    grp_pow_generic_double_s_fu_372_ap_ready;
reg   [1:0] i_0_reg_203;
wire    ap_CS_fsm_state7;
reg   [5:0] i_1_0_reg_215;
wire    ap_CS_fsm_state93;
reg   [1:0] i_2_0_reg_226;
wire    ap_CS_fsm_state122;
reg   [31:0] mean_value_y_0_0_reg_238;
wire   [0:0] icmp_ln38_fu_601_p2;
reg   [31:0] mean_value_x_0_0_reg_250;
reg   [31:0] count_0_0_reg_262;
reg   [5:0] j_1_0_reg_274;
reg    grp_pow_generic_double_s_fu_285_ap_start_reg;
reg   [121:0] ap_NS_fsm;
wire    ap_NS_fsm_state18;
wire    ap_CS_fsm_state18;
reg    grp_pow_generic_double_s_fu_314_ap_start_reg;
reg    grp_pow_generic_double_s_fu_343_ap_start_reg;
reg    grp_pow_generic_double_s_fu_372_ap_start_reg;
wire   [63:0] zext_ln14_fu_498_p1;
wire   [63:0] zext_ln44_fu_625_p1;
wire   [63:0] zext_ln52_fu_676_p1;
wire   [31:0] grp_fu_419_p2;
wire   [31:0] grp_fu_425_p2;
reg   [31:0] grp_fu_401_p0;
reg   [31:0] grp_fu_401_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state97;
reg   [31:0] grp_fu_405_p0;
reg   [31:0] grp_fu_405_p1;
wire    ap_CS_fsm_state107;
reg   [31:0] grp_fu_431_p0;
wire    ap_CS_fsm_state90;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state85;
wire   [31:0] bitcast_ln29_fu_522_p1;
wire   [31:0] bitcast_ln29_1_fu_539_p1;
wire   [7:0] tmp_9_fu_525_p4;
wire   [22:0] trunc_ln29_fu_535_p1;
wire   [7:0] tmp_10_fu_542_p4;
wire   [22:0] trunc_ln29_1_fu_552_p1;
wire   [0:0] or_ln29_fu_580_p2;
wire   [0:0] or_ln29_1_fu_584_p2;
wire   [0:0] and_ln29_fu_588_p2;
wire   [0:0] grp_fu_455_p2;
wire   [1:0] zext_ln44_1_fu_638_p1;
wire   [31:0] add_ln47_fu_648_p2;
reg   [1:0] grp_fu_401_opcode;
reg   [1:0] grp_fu_405_opcode;
wire   [0:0] icmp_ln13_fu_486_p2;

// power-on initialization
initial begin
#0 ap_CS_fsm = 122'd1;
#0 grp_pow_generic_double_s_fu_285_ap_start_reg = 1'b0;
#0 grp_pow_generic_double_s_fu_314_ap_start_reg = 1'b0;
#0 grp_pow_generic_double_s_fu_343_ap_start_reg = 1'b0;
#0 grp_pow_generic_double_s_fu_372_ap_start_reg = 1'b0;
end

kmeans_x_data #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
x_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_data_address0),
    .ce0(x_data_ce0),
    .q0(x_data_q0)
);

kmeans_y_data #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
y_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_data_address0),
    .ce0(y_data_ce0),
    .q0(y_data_q0)
);

kmeans_data_clustBew #(
    .DataWidth( 1 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
data_cluster_id_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_cluster_id_address0),
    .ce0(data_cluster_id_ce0),
    .we0(data_cluster_id_we0),
    .d0(data_cluster_id_d0),
    .q0(data_cluster_id_q0)
);

pow_generic_double_s grp_pow_generic_double_s_fu_285(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pow_generic_double_s_fu_285_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_285_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_285_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_285_ap_ready),
    .base_r(x_assign_reg_758),
    .ap_return(grp_pow_generic_double_s_fu_285_ap_return)
);

pow_generic_double_s grp_pow_generic_double_s_fu_314(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pow_generic_double_s_fu_314_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_314_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_314_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_314_ap_ready),
    .base_r(x_assign_1_reg_763),
    .ap_return(grp_pow_generic_double_s_fu_314_ap_return)
);

pow_generic_double_s grp_pow_generic_double_s_fu_343(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pow_generic_double_s_fu_343_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_343_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_343_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_343_ap_ready),
    .base_r(x_assign_2_reg_768),
    .ap_return(grp_pow_generic_double_s_fu_343_ap_return)
);

pow_generic_double_s grp_pow_generic_double_s_fu_372(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pow_generic_double_s_fu_372_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_372_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_372_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_372_ap_ready),
    .base_r(x_assign_3_reg_773),
    .ap_return(grp_pow_generic_double_s_fu_372_ap_return)
);

kmeans_faddfsub_3CeG #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_faddfsub_3CeG_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_401_p0),
    .din1(grp_fu_401_p1),
    .opcode(grp_fu_401_opcode),
    .ce(1'b1),
    .dout(grp_fu_401_p2)
);

kmeans_faddfsub_3CeG #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_faddfsub_3CeG_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_405_p0),
    .din1(grp_fu_405_p1),
    .opcode(grp_fu_405_opcode),
    .ce(1'b1),
    .dout(grp_fu_405_p2)
);

kmeans_fsub_32ns_DeQ #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_fsub_32ns_DeQ_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_467),
    .din1(centroids_x_load_1_reg_705),
    .ce(1'b1),
    .dout(grp_fu_409_p2)
);

kmeans_fsub_32ns_DeQ #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_fsub_32ns_DeQ_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_474),
    .din1(centroids_y_load_1_reg_710),
    .ce(1'b1),
    .dout(grp_fu_413_p2)
);

kmeans_fdiv_32ns_Ee0 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_fdiv_32ns_Ee0_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mean_value_x_0_0_reg_250),
    .din1(tmp_5_reg_896),
    .ce(1'b1),
    .dout(grp_fu_419_p2)
);

kmeans_fdiv_32ns_Ee0 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_fdiv_32ns_Ee0_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mean_value_y_0_0_reg_238),
    .din1(tmp_5_reg_896),
    .ce(1'b1),
    .dout(grp_fu_425_p2)
);

kmeans_sitofp_32nFfa #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kmeans_sitofp_32nFfa_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_431_p0),
    .ce(1'b1),
    .dout(grp_fu_431_p1)
);

kmeans_fptrunc_64Gfk #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
kmeans_fptrunc_64Gfk_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_798),
    .ce(1'b1),
    .dout(grp_fu_437_p1)
);

kmeans_fptrunc_64Gfk #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
kmeans_fptrunc_64Gfk_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_8_reg_803),
    .ce(1'b1),
    .dout(grp_fu_440_p1)
);

kmeans_fpext_32nsHfu #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
kmeans_fpext_32nsHfu_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_738),
    .ce(1'b1),
    .dout(grp_fu_443_p1)
);

kmeans_fpext_32nsHfu #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
kmeans_fpext_32nsHfu_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_743),
    .ce(1'b1),
    .dout(grp_fu_446_p1)
);

kmeans_fpext_32nsHfu #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
kmeans_fpext_32nsHfu_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_748),
    .ce(1'b1),
    .dout(grp_fu_449_p1)
);

kmeans_fpext_32nsHfu #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
kmeans_fpext_32nsHfu_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_753),
    .ce(1'b1),
    .dout(grp_fu_452_p1)
);

kmeans_fcmp_32ns_IfE #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
kmeans_fcmp_32ns_IfE_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(distance_reg_814),
    .din1(min_distance_s_reg_808),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_455_p2)
);

kmeans_dadd_64ns_JfO #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
kmeans_dadd_64ns_JfO_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i_reg_778),
    .din1(tmp_i1_reg_783),
    .ce(1'b1),
    .dout(grp_fu_459_p2)
);

kmeans_dadd_64ns_JfO #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
kmeans_dadd_64ns_JfO_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i2_reg_788),
    .din1(tmp_i3_reg_793),
    .ce(1'b1),
    .dout(grp_fu_463_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pow_generic_double_s_fu_285_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state18) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_pow_generic_double_s_fu_285_ap_start_reg <= 1'b1;
        end else if ((grp_pow_generic_double_s_fu_285_ap_ready == 1'b1)) begin
            grp_pow_generic_double_s_fu_285_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pow_generic_double_s_fu_314_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state18) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_pow_generic_double_s_fu_314_ap_start_reg <= 1'b1;
        end else if ((grp_pow_generic_double_s_fu_314_ap_ready == 1'b1)) begin
            grp_pow_generic_double_s_fu_314_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pow_generic_double_s_fu_343_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state18) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_pow_generic_double_s_fu_343_ap_start_reg <= 1'b1;
        end else if ((grp_pow_generic_double_s_fu_343_ap_ready == 1'b1)) begin
            grp_pow_generic_double_s_fu_343_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pow_generic_double_s_fu_372_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state18) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_pow_generic_double_s_fu_372_ap_start_reg <= 1'b1;
        end else if ((grp_pow_generic_double_s_fu_372_ap_ready == 1'b1)) begin
            grp_pow_generic_double_s_fu_372_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_601_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state94))) begin
        count_0_0_reg_262 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state101)) begin
        count_0_0_reg_262 <= select_ln44_2_reg_881;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_203 <= i_reg_690;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_203 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_0_reg_215 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state93)) begin
        i_1_0_reg_215 <= add_ln24_reg_718;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_504_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        i_2_0_reg_226 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state122)) begin
        i_2_0_reg_226 <= add_ln38_reg_843;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_601_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state94))) begin
        j_1_0_reg_274 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state101)) begin
        j_1_0_reg_274 <= add_ln43_reg_851;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_601_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state94))) begin
        mean_value_x_0_0_reg_250 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state101)) begin
        mean_value_x_0_0_reg_250 <= select_ln44_1_fu_669_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_601_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state94))) begin
        mean_value_y_0_0_reg_238 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state101)) begin
        mean_value_y_0_0_reg_238 <= select_ln44_fu_662_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln24_reg_718 <= add_ln24_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state94)) begin
        add_ln38_reg_843 <= add_ln38_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state95)) begin
        add_ln43_reg_851 <= add_ln43_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        centroids_x_load_1_reg_705 <= centroids_x_q1;
        centroids_x_load_reg_695 <= centroids_x_q0;
        centroids_y_load_1_reg_710 <= centroids_y_q1;
        centroids_y_load_reg_700 <= centroids_y_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state91)) begin
        distance_reg_814 <= grp_fu_440_p1;
        min_distance_s_reg_808 <= grp_fu_437_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_690 <= i_fu_492_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state92)) begin
        icmp_ln29_1_reg_825 <= icmp_ln29_1_fu_562_p2;
        icmp_ln29_2_reg_830 <= icmp_ln29_2_fu_568_p2;
        icmp_ln29_3_reg_835 <= icmp_ln29_3_fu_574_p2;
        icmp_ln29_reg_820 <= icmp_ln29_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state96)) begin
        icmp_ln44_reg_875 <= icmp_ln44_fu_642_p2;
        select_ln44_2_reg_881 <= select_ln44_2_fu_654_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state95))) begin
        icmp_ln51_reg_871 <= icmp_ln51_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state96) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_467 <= x_data_q0;
        reg_474 <= y_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_1_reg_748 <= grp_fu_409_p2;
        tmp_2_reg_743 <= grp_fu_405_p2;
        tmp_3_reg_753 <= grp_fu_413_p2;
        tmp_s_reg_738 <= grp_fu_401_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state89)) begin
        tmp_4_reg_798 <= grp_fu_459_p2;
        tmp_8_reg_803 <= grp_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state106)) begin
        tmp_5_reg_896 <= grp_fu_431_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        tmp_i1_reg_783 <= grp_pow_generic_double_s_fu_314_ap_return;
        tmp_i2_reg_788 <= grp_pow_generic_double_s_fu_343_ap_return;
        tmp_i3_reg_793 <= grp_pow_generic_double_s_fu_372_ap_return;
        tmp_i_reg_778 <= grp_pow_generic_double_s_fu_285_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        x_assign_1_reg_763 <= grp_fu_446_p1;
        x_assign_2_reg_768 <= grp_fu_449_p1;
        x_assign_3_reg_773 <= grp_fu_452_p1;
        x_assign_reg_758 <= grp_fu_443_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_504_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        zext_ln25_reg_723[5 : 0] <= zext_ln25_fu_516_p1[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_601_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state94))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_601_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state94))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        centroids_x_address0 = zext_ln14_fu_498_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroids_x_address0 = 1'd0;
    end else begin
        centroids_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        centroids_x_address1 = zext_ln52_fu_676_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroids_x_address1 = 1'd1;
    end else begin
        centroids_x_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        centroids_x_ce0 = 1'b1;
    end else begin
        centroids_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state122) | (1'b1 == ap_CS_fsm_state2))) begin
        centroids_x_ce1 = 1'b1;
    end else begin
        centroids_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        centroids_x_we0 = 1'b1;
    end else begin
        centroids_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_state122))) begin
        centroids_x_we1 = 1'b1;
    end else begin
        centroids_x_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        centroids_y_address0 = zext_ln14_fu_498_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroids_y_address0 = 1'd0;
    end else begin
        centroids_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        centroids_y_address1 = zext_ln52_fu_676_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        centroids_y_address1 = 1'd1;
    end else begin
        centroids_y_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2))) begin
        centroids_y_ce0 = 1'b1;
    end else begin
        centroids_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state122) | (1'b1 == ap_CS_fsm_state2))) begin
        centroids_y_ce1 = 1'b1;
    end else begin
        centroids_y_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        centroids_y_we0 = 1'b1;
    end else begin
        centroids_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_reg_871 == 1'd0) & (1'b1 == ap_CS_fsm_state122))) begin
        centroids_y_we1 = 1'b1;
    end else begin
        centroids_y_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state95)) begin
        data_cluster_id_address0 = zext_ln44_fu_625_p1;
    end else if ((1'b1 == ap_CS_fsm_state93)) begin
        data_cluster_id_address0 = zext_ln25_reg_723;
    end else begin
        data_cluster_id_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state93) | (1'b1 == ap_CS_fsm_state95))) begin
        data_cluster_id_ce0 = 1'b1;
    end else begin
        data_cluster_id_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state93)) begin
        data_cluster_id_we0 = 1'b1;
    end else begin
        data_cluster_id_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_401_opcode = 2'd1;
    end else if (((icmp_ln44_reg_875 == 1'd1) & (1'b1 == ap_CS_fsm_state97))) begin
        grp_fu_401_opcode = 2'd0;
    end else begin
        grp_fu_401_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state97)) begin
        grp_fu_401_p0 = mean_value_x_0_0_reg_250;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_401_p0 = reg_467;
    end else begin
        grp_fu_401_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state97)) begin
        grp_fu_401_p1 = reg_467;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_401_p1 = centroids_x_load_reg_695;
    end else begin
        grp_fu_401_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_405_opcode = 2'd1;
    end else if (((icmp_ln44_reg_875 == 1'd1) & (1'b1 == ap_CS_fsm_state97))) begin
        grp_fu_405_opcode = 2'd0;
    end else begin
        grp_fu_405_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state97)) begin
        grp_fu_405_p0 = mean_value_y_0_0_reg_238;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_405_p0 = reg_474;
    end else begin
        grp_fu_405_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state97)) begin
        grp_fu_405_p1 = reg_474;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_405_p1 = centroids_y_load_reg_700;
    end else begin
        grp_fu_405_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state95)) begin
        grp_fu_431_p0 = count_0_0_reg_262;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_431_p0 = zext_ln13_fu_481_p1;
    end else begin
        grp_fu_431_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state95)) begin
        x_data_address0 = zext_ln44_fu_625_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        x_data_address0 = zext_ln25_fu_516_p1;
    end else begin
        x_data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state95) | (1'b1 == ap_CS_fsm_state9))) begin
        x_data_ce0 = 1'b1;
    end else begin
        x_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state95)) begin
        y_data_address0 = zext_ln44_fu_625_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        y_data_address0 = zext_ln25_fu_516_p1;
    end else begin
        y_data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state95) | (1'b1 == ap_CS_fsm_state9))) begin
        y_data_ce0 = 1'b1;
    end else begin
        y_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln13_fu_486_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln24_fu_504_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state94;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state94 : begin
            if (((icmp_ln38_fu_601_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state94))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state95;
            end
        end
        ap_ST_fsm_state95 : begin
            if (((icmp_ln51_fu_632_p2 == 1'd1) & (icmp_ln43_fu_613_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state95))) begin
                ap_NS_fsm = ap_ST_fsm_state122;
            end else if (((icmp_ln43_fu_613_p2 == 1'd1) & (icmp_ln51_fu_632_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state95))) begin
                ap_NS_fsm = ap_ST_fsm_state102;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state96;
            end
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_510_p2 = (i_1_0_reg_215 + 6'd1);

assign add_ln38_fu_607_p2 = (i_2_0_reg_226 + 2'd1);

assign add_ln43_fu_619_p2 = (j_1_0_reg_274 + 6'd1);

assign add_ln47_fu_648_p2 = (count_0_0_reg_262 + 32'd1);

assign and_ln29_fu_588_p2 = (or_ln29_fu_580_p2 & or_ln29_1_fu_584_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state101 = ap_CS_fsm[32'd100];

assign ap_CS_fsm_state106 = ap_CS_fsm[32'd105];

assign ap_CS_fsm_state107 = ap_CS_fsm[32'd106];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state122 = ap_CS_fsm[32'd121];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd84];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign ap_CS_fsm_state91 = ap_CS_fsm[32'd90];

assign ap_CS_fsm_state92 = ap_CS_fsm[32'd91];

assign ap_CS_fsm_state93 = ap_CS_fsm[32'd92];

assign ap_CS_fsm_state94 = ap_CS_fsm[32'd93];

assign ap_CS_fsm_state95 = ap_CS_fsm[32'd94];

assign ap_CS_fsm_state96 = ap_CS_fsm[32'd95];

assign ap_CS_fsm_state97 = ap_CS_fsm[32'd96];

assign ap_NS_fsm_state18 = ap_NS_fsm[32'd17];

assign bitcast_ln29_1_fu_539_p1 = min_distance_s_reg_808;

assign bitcast_ln29_fu_522_p1 = distance_reg_814;

assign centroids_x_d0 = grp_fu_431_p1;

assign centroids_x_d1 = grp_fu_419_p2;

assign centroids_y_d0 = grp_fu_431_p1;

assign centroids_y_d1 = grp_fu_425_p2;

assign data_cluster_id_d0 = (grp_fu_455_p2 & and_ln29_fu_588_p2);

assign grp_pow_generic_double_s_fu_285_ap_start = grp_pow_generic_double_s_fu_285_ap_start_reg;

assign grp_pow_generic_double_s_fu_314_ap_start = grp_pow_generic_double_s_fu_314_ap_start_reg;

assign grp_pow_generic_double_s_fu_343_ap_start = grp_pow_generic_double_s_fu_343_ap_start_reg;

assign grp_pow_generic_double_s_fu_372_ap_start = grp_pow_generic_double_s_fu_372_ap_start_reg;

assign i_fu_492_p2 = (i_0_reg_203 + 2'd1);

assign icmp_ln13_fu_486_p2 = ((i_0_reg_203 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_504_p2 = ((i_1_0_reg_215 == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln29_1_fu_562_p2 = ((trunc_ln29_fu_535_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln29_2_fu_568_p2 = ((tmp_10_fu_542_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln29_3_fu_574_p2 = ((trunc_ln29_1_fu_552_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_556_p2 = ((tmp_9_fu_525_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_601_p2 = ((i_2_0_reg_226 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_613_p2 = ((j_1_0_reg_274 == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_642_p2 = ((zext_ln44_1_fu_638_p1 == i_2_0_reg_226) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_632_p2 = ((count_0_0_reg_262 == 32'd0) ? 1'b1 : 1'b0);

assign or_ln29_1_fu_584_p2 = (icmp_ln29_3_reg_835 | icmp_ln29_2_reg_830);

assign or_ln29_fu_580_p2 = (icmp_ln29_reg_820 | icmp_ln29_1_reg_825);

assign select_ln44_1_fu_669_p3 = ((icmp_ln44_reg_875[0:0] === 1'b1) ? grp_fu_401_p2 : mean_value_x_0_0_reg_250);

assign select_ln44_2_fu_654_p3 = ((icmp_ln44_fu_642_p2[0:0] === 1'b1) ? add_ln47_fu_648_p2 : count_0_0_reg_262);

assign select_ln44_fu_662_p3 = ((icmp_ln44_reg_875[0:0] === 1'b1) ? grp_fu_405_p2 : mean_value_y_0_0_reg_238);

assign tmp_10_fu_542_p4 = {{bitcast_ln29_1_fu_539_p1[30:23]}};

assign tmp_9_fu_525_p4 = {{bitcast_ln29_fu_522_p1[30:23]}};

assign trunc_ln29_1_fu_552_p1 = bitcast_ln29_1_fu_539_p1[22:0];

assign trunc_ln29_fu_535_p1 = bitcast_ln29_fu_522_p1[22:0];

assign zext_ln13_fu_481_p1 = i_0_reg_203;

assign zext_ln14_fu_498_p1 = i_0_reg_203;

assign zext_ln25_fu_516_p1 = i_1_0_reg_215;

assign zext_ln44_1_fu_638_p1 = data_cluster_id_q0;

assign zext_ln44_fu_625_p1 = j_1_0_reg_274;

assign zext_ln52_fu_676_p1 = i_2_0_reg_226;

always @ (posedge ap_clk) begin
    zext_ln25_reg_723[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //kmeans
